### ISSUE TITLE
Default display settings too bright

### ISSUE THREAD

**Issue by tischi** [mobie/arabidopsis-root-lm-project#1]
@constantinpape @K-Meech 

This is the default:

<img width="877" alt="image" src="https://user-images.githubusercontent.com/2157566/110936852-ccf24e00-8331-11eb-947c-cfefe2e732ec.png">

This looks better:

<img width="877" alt="image" src="https://user-images.githubusercontent.com/2157566/110936886-d8457980-8331-11eb-99cd-47948718479f.png">

**Comment by constantinpape** [comment]
@tischi something is not working quite correctly there: I am setting different defaults in the `images.json`:
https://github.com/mobie/arabidopsis-root-lm-datasets/blob/master/data/arabidopsis-root/images/images.json#L17-L20
But somehow they are not accepted, although I can't find any typo.
Also note that the contrast limits for the nuclei work:
https://github.com/mobie/arabidopsis-root-lm-datasets/blob/master/data/arabidopsis-root/images/images.json#L29-L32

**Comment by constantinpape** [comment]
Ah, I just realized that it loads the settings from the default bookmark instead of the `images.json`. I will fix it.

**Comment by constantinpape** [comment]
Fixed it.
