### ISSUE TITLE
Label index 0.0

### ISSUE THREAD

**Issue by tischi** [mobie/arabidopsis-root-lm-project#2]
@constantinpape 

I don't get what is going on.

When I select an object with label index 0.0 I get the whole root:

<img width="915" alt="image" src="https://user-images.githubusercontent.com/2157566/110940803-c535a800-8337-11eb-95fc-aad28c040b61.png">

Then the individual cells would have be **inside** of that root, which cannot be, because the label image can only have one value at any given position....I am confused 😕

**Comment by tischi** [comment]
I have an idea, maybe it creates a mesh for the background and we are kind of looking from inside the background outward :-)

We may have never seen this, because I think selecting the label 0 within BDV may be disabled...

**Comment by constantinpape** [comment]
> I have an idea, maybe it creates a mesh for the background and we are kind of looking from inside the background outward :-)
> 

Yes, that's what it looks like.

> We may have never seen this, because I think selecting the label 0 within BDV may be disabled...

Why can you select it here though?

**Comment by tischi** [comment]
> Why can you select it here though?

I have selected it by chance in the table, I have never tried this before.
Not sure what to do, it is kind of cool to be able to see it.
Maybe we should also enable it in BDV?

**Comment by constantinpape** [comment]
> I have selected it by chance in the table, I have never tried this before.
> Not sure what to do, it is kind of cool to be able to see it.
> Maybe we should also enable it in BDV?

It looks cool here, but I am not sure it's such a good idea to enable selecting it in BDV. The background should be treated specially and selecting it doesn't make much sense to me.

**Comment by tischi** [comment]
OK, I will have a look and disable the selection in the table as well.
Maybe we should show a message window though: "Labels with index 0 cannot be selected as those are considered background" ?!

**Comment by constantinpape** [comment]
> OK, I will have a look and disable the selection in the table as well.
> Maybe we should show a message window though: "Labels with index 0 cannot be selected as those are considered background" ?!

Yes, that's a good point.

**Comment by constantinpape** [comment]
This is fixed now.
